name: Markdown Mimic Workflow
on:
  push:
    branches:
      - main
jobs:
  Markdown-Mimic-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Markdown Mimic
        uses: grokdesigns/markdown-mimic@dev
        with:
          git_username: 'github-actions[bot]'
          git_email: 'github-actions[bot]@users.noreply.github.com'
          skip_ci: 'yes' #BE VERY CAREFUL CHANGING THIS. IT COULD CREATE INFINITE WORKFLOWS.
          commit_message: '🤖 - Generated via Markdown Mimic'
          file_exts: 'md,txt'
          output_folder: 'outputs'
          input_folder: 'templates'
          branch_name: ${{ github.ref }}  #Don't change.
          overwrite_original: 1
